### ISSUE TITLE
Hoaxy backend install issue

### ISSUE THREAD

**Issue by mapsiva** [IUNetSci/hoaxy-backend#11]
Hi, I'm trying to install hoaxy backend on my ubuntu server, but pylucene doesn't install. When I perform `make test` my jvm throws an exception. See below:

Installed /tmp/pylucene/pylucene-4.10.1-1/build/test/lucene-4.10.1-py2.7-linux-x86_64.egg
Processing dependencies for lucene==4.10.1
Finished processing dependencies for lucene==4.10.1
find test -name 'test_*.py' | PYTHONPATH=/tmp/pylucene/pylucene-4.10.1-1/build/test xargs -t -n 1 /usr/local/bin/python
/usr/local/bin/python test/test_BooleanQuery.py 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002b3c1c1495e8, pid=7399, tid=47537106197888
#
# JRE version: OpenJDK Runtime Environment (7.0_171-b02) (build 1.7.0_171-b02)
# Java VM: OpenJDK 64-Bit Server VM (24.171-b02 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.13
# Distribution: Ubuntu 14.04 LTS, package 7u171-2.6.13-0ubuntu0.14.04.2
# Problematic frame:
# V  [libjvm.so+0x61b5e8]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/pylucene/pylucene-4.10.1-1/hs_err_pid7399.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
xargs: /usr/local/bin/python: terminated by signal 6
make: *** [test] Error 125
root@blackbird:/tmp/pylucene/pylucene-4.10.1-1# python --version
Python 2.7.12

Does anyone knows any solution for this issue? 

Regards,
Márcio Silva

**Comment by filmenczer** [comment]
@shaochengcheng are you able to respond to this query?

**Comment by shaochengcheng** [comment]
Hi mapsiva,

Thanks for trying Hoaxy. The error was probably related to the JDK, which is out of my knowledge. And I noticed that this happened to someone before:
  - https://stackoverflow.com/questions/26904725/pylucene-error-with-icetea-jdk-jre/29607100
  - http://grokbase.com/t/lucene/pylucene-dev/092d7zczd6/make-test-doesnt-work-before-install

These Q&A could give you some hints.

Moreover, I also noticed that you were install pylucene as user `root`. As we documented, please create a virtual python environment and do not use `root` account to install these packages, otherwise the system libraries may conflict your installation. You should always make sure that the python you used to compile jcc and running pylucene is the same version.

Well, it often happens that some unknown problems could occur during the installation of pylucene. I am so sorry that I never met your situation. The simple suggestions I could offer are:
  - Follow our instruction and use normal user to try to compile and install pylucene again.
  - If it fails, maybe switch to another version of JDK, e.g., 1.8

If you have knowledge of reading java logs, try to dump the debugging information. I am so sorry that I can not replicate your problem.

Hope you have a good luck!

Chengcheng

**Comment by glciampaglia** [comment]
Closing for now but feel free to reopen.
