### ISSUE TITLE
generate_top_spreaders broken by changes in the database

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-backend#12]
We noticed that the dashboard for top influential users is empty. After some investigation, we discovered that the [cron job that populates the table](https://github.com/IUNetSci/hoaxy-backend/blob/master/hoaxy/commands/report.py#L136) does not work anymore, probably due to the recent changes in the database. 

Can you please update the two queries that calculate the most influential users for claims and fact-checks?

**Comment by shaochengcheng** [comment]
Hi @glciampaglia,

After checking the code, I found out that it was not caused by the database queries. It was a bug of our new tweet parser. I forgot to parse `retweeted_status_id`, `quoted_status_id`, and `in_reply_to_status_id` into `ass_tweet` table, thus the actual queries cannot evaluate the number of retweets of a user (measurement of the influence of a user).

Now the bug is fixed. And the lost part of the `ass_tweet` table is also patched. But I only re-calculate the most influential users of `upper_day='2018-05-10`.

Thanks
Chengcheng

**Comment by filmenczer** [comment]
Fantastic!! Thank you @shaochengcheng !!
