### ISSUE TITLE
Consider new search fields

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-backend#23]
As part of the migration to Python 3 #20, we had to make some changes to the [indexing class](/IUNetSci/hoaxy-backend/blob/master/hoaxy/ir/index.py) of Hoaxy. It would be nice to see if there are additional fields that would be worth indexing. For example, we might want to search only by domain (e.g. breitbart, infowars), or by language (e.g. Portoguese, Spanish).

**Comment by filmenczer** [comment]
Language would be difficult, maybe require Solr -- deferred until a future time. But we could index by domain and/or domain type (tag). This would require two steps:
1. Re-index existing collection via Lucene
2. Modify the cron job that indexes new incoming document
3. Modify the API so that it accepts the new parameters
