### ISSUE TITLE
Parse tweets and store all edges into an edge table

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-backend#4]
To speed up network generation queries, we will create an `edge` table and will add rows to it by parsing each tweet and extracting all replies, mentions, retweets, and quotes.

**Comment by filmenczer** [comment]
I added my interpretations. But if they cannot be implemented easily and efficiently, I am happy to give up on some edges!

**Comment by glciampaglia** [comment]
It looks like that `is_mention` and `tweet_type` have been swapped and this breaks Hoaxy (both the demo site and probably the old Hoaxy). @shaochengcheng can you please take a look at it?

This is the output of "Test Endpoint" from mashape:

```
      "canonical_url": "http://www.snopes.com/clinton-secret-earpiece-debate/",
      "date_published": "2016-09-27T22:37:20.351Z",
      "domain": "snopes.com",
      "from_user_id": 743076627605684200,
      "from_user_screen_name": "caliwaterman",
      "id": 68363,
      "is_mention": "retweet",
      "site_type": "fact_checking",
      "title": "FALSE: Hillary Clinton Wore Secret Earpiece During First Presidential Debate",
      "to_user_id": 724756382663082000,
      "to_user_screen_name": "LesFoster6",
      "tweet_created_at": "2016-09-28T03:52:41.000Z",
      "tweet_id": "780978510076620804",
      "tweet_type": false,
      "url_id": 1418261
```

**Comment by shaochengcheng** [comment]
Sorry that I made such a dummy error!. I fixed this bug.

Thanks
Chengcheng

**Comment by filmenczer** [comment]
Does the new network API mean that this issue is closed, or is this still work in progress? I would expect a large speed up by indexing edges. In the OSoMe network tool the speed up was amazing, at least x10.

**Comment by filmenczer** [comment]
@shaochengcheng -- Giovanni and I looked at your new API function `db_query_network` using the new network table `twitter_network_edge` and noticed that it was kind of slow because of two sequential scans. We added an index for field `group_id` on table `article` and the index for field `article_id` on table `url`. After this, the query uses index scans only, and is super fast!!!!

Please be sure to update the code that creates these tables to include these two indexes. Then you can close this issue.

**Comment by shaochengcheng** [comment]
Great! Will update the code!

Thanks
Chengcheng
