### ISSUE TITLE
Facebook interface? (and CI)

### ISSUE THREAD

**Issue by mohawk2** [IUNetSci/hoaxy-backend#57]
This is a really impressive project, and also in this era a genuinely important one. I have two questions:
- is there an appetite for making it also look at Facebook information the way it does for Twitter?
- is there an appetite for a continuous integration setup?

**Comment by filmenczer** [comment]
Facebook does not have an API that we could use in a similar way to Twitter.

**Comment by filmenczer** [comment]
Given our finite resources, we are unable to use continuous integration at this time. But thanks for the offer!

**Comment by mohawk2** [comment]
Well, I was offering to write you a Travis config that would help you, but if you're not interested that's Ok.

Similarly, I believe that the current Twitter MO is:
- gather sites to filter by
- open stream from Twitter filtered by those sites
- process incoming tweets

A Facebook one could be:
- gather sites to filter by
- for each of those, query Facebook's Graph API for connected activity since the last query on that
- process each response

Do I correctly understand you're not interested? All it would need on top of that would be a bit of decoupling of the current commands bit to allow more than one social network.

**Comment by glciampaglia** [comment]
Hi @mohawk2, thanks for the suggestion. Let me expand a bit on what @filmenczer mentioned. As far as continuous integration goes, the problem is that our team has limited resources to devote to Hoaxy, and so CI could be impractical for us. We mostly commit medium/large changes on a less frequent basis than what CI typically recommends, so our main concern is that having Travis builds in place would lead to more problems than solutions.

As for the Facebook model, we explored in the past something similar to what you suggest, and we found two big problems: the first is that the Facebook Graph API does not offer a streaming endpoint. This means one would need to make use of REST calls to gather the data on a regular basis. This would mean writing a complete new subsystem from scratch, which would require a big integration effort. If Facebook provided a streaming endpoint at least for posts to public pages, then things would be much easier to implement. 

The second problem is that Facebook is not as dependable as Twitter when it comes to its API. In the past they have turned off developer access without giving any advance notice to developers, so we are afraid that even if one found a decent workaround for collecting posts to public pages, things could still break overnight due to changes in their access policies.

I hope it makes sense. Thanks again for your interest in Hoaxy, and if you have any comment or suggestion feel free to write us here. Cheers!
