### ISSUE TITLE
Comply with new Twitter API

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#59]
We need to update our code to comply with the new format of the streaming API: https://blog.twitter.com/developer/en_us/topics/tools/2020/introducing_new_twitter_api.html

**Comment by filmenczer** [comment]
@shaochengcheng would you like to look into the new Twitter API v2 that was just released: https://developer.twitter.com/en/docs/twitter-api/early-access
We need to make changes in preparation for the deprecation of v1.

**Comment by shaochengcheng** [comment]
Hi @filmenczer, I just roughly went through the documentation of version 2. Honestly speaking, it is a big improvement that gives us finer control over Twitter data. But this big change also means a lot of work to migrate, I would like to present my two main concerns.

1. About the limits for the number of tweets. According to the [Filtered Stream API Reference](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream), the basic access level is 500,000 Tweets per month per project, which is far from our needs.

2. The fundamental data model changed a lot. The two main object `tweet` and `user` data models have been dramatically changed in version two, please check [v1.1](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview/intro-to-tweet-json) and [v2](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet). In simple words, in the data model version 2, only a small set of fields are set as default returned, and several new fields are introduced as well. In fact, the [API migration](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/migrate) documented that (the returned tweet objects format is) 'determined by `fields` and `expansions` request parameters, not backward-compatible with v1.1 formats'. All of these indicate a huge work on migration. 

There are also good news from the new APIs:

1. Direct search of the URL string, instead of searching the whole tweet;
2. No need to unshorten URLs anymore, as the introduction of `entities.urls.expanded_url`;
3. A better way to handle reply and quote type, as the introduction of `referenced_tweets`.

We can have a meeting about the code migration to talk about the technical details.

Thanks
Chengcheng
