### ISSUE TITLE
Fix for Botometer-v4

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#60]
The back-end (via a cron job) calles the Botometer Pro API to populate the bot scores in the dashboard (https://hoaxy.iuni.iu.edu/stats.php#influential_users and https://hoaxy.iuni.iu.edu/stats.php#active_users). We need to not only update the botometer-python package, but also unsubscribe to the old (Pro) plan and subscribe to the new (Basic) plan.

**Comment by yangkcatiu** [comment]
I resubscribed to the new Basic plan on RapidAPI so the frontend is working.

The backend is using the same key so it should be working too. However, it just occurred to me that since we adjust the response of the Botometer API, the Hoaxy backend probably also need some adjustment in addition to upgrade the botometer-python package.

**Comment by filmenczer** [comment]
See README at https://github.com/IUNetSci/botometer-python

**Comment by benabus** [comment]
@chathuriw fixed this
